let BOOKS = [
"The New Jim Crow: Mass Incarceration in the Age Colorblindness",
"London Fields",
"Modern Philosophy: An Anthology of Primary Sources",
"Modern Philosophy: An Anthology of Primary Sources",
"The Metaphysics",
"Wordsmith: A Guide to Paragraphs & Short Essays",
"Oryx and Crake",
"The Handmaid's Tale",
"The Sense of an Ending",
"On Crimes and Punishment",
"Castle: Cross-Sections",
"Understanding Asexuality",
"The Martian Chronicles",
"Life of Galileo",
"Agnes Grey",
"The World of Late Antiquity",
"Norton Anthology of Western Music",
"Mysteries of the Middles Ages",
"Carcassi: Melodic and Progressive Studies, Op. 60",
"How to Win Friends & Influence People",
"An Ottoman Traveller",
"Utz",
"The Awakening",
"Selected Political Speeches",
"Between The World And Me",
"We Were Eight Years in Power: An American Tragedy",
"The Idea of History",
"The Science Book",
"The Science Book",
"The Science Book",
"City of Djinns: A Year in Delhi",
"The Last Mughal: The Fall of a Dynasty, Delhi 1857",
"Women, Race, & Class",
"End Zone",
"Separate and Dominate: Feminism and Racism after The War On Terror",
"Crime and Punishment",
"Think Python",
"The Three Musketeers",
"Charlemagne's Courtier: The Complete Einhard",
"Charlemagne's Courtier: The Complete Einhard",
"Collected Poems 1909 - 1962",
"Backlash: The Undeclared War Against American Women",
"The Great Degeneration: How Institutions Decay and Economies Die",
"My Brilliant Friend",
"The Story of a New Name",
"Those Who Leave and Those Who Stay",
"Tender is the Night",
"The Great Gatsby",
"Mitos Mexicanos",
"Discipline & Punish: The Birth of the Prison",
"Ethics: Subjectivity and Truth, Vol I",
"The Order of Things: An Archaeology of the Human Sciences",
"The Chomsky-Foucault Debate: On Human Nature",
"The Chomsky-Foucault Debate: On Human Nature",
"The Silk Roads: A New History of the World",
"Pedagogy of the Opressed",
"Epistemology",
"Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch",
"Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch",
"Broken Man / Hombre Roto",
"Bad Feminist",
"Readings in Medieval History",
"Sea of Poppies",
"The Intelligent Investor: The Definitive Book on Value Investing",
"The Elements: A Visual Exploration of Every Known Atom in the Universe",
"The Fault in Our Stars",
"The Darkest Dark",
"The Meaning of Hitler",
"Exit West",
"Homo Deus: A Brief History of Tomorrow",
"The Protestant Reformation",
"God Is Not Great",
"The Portable Atheist",
"An Equiry Concerned Human Understading: A Letter from a Gentleman to his Friend in Edinburgh",
"Introduction To Early Medieval Western Europe, 300 - 900: The Sword, The Plough, and The Book",
"Socrates on Trial",
"The Death and Life of Great American Cities",
"Napoleon",
"Letter to Father",
"Thinking, Fast and Slow",
"Let's Talk About Love",
"Prolegomena to Any Future Metaphysics",
"The Roman Empire: A Very Short Introduction",
"In the Matter of J. Robert Oppenheimer",
"The Cambridge Companion to Renaissance Humanism",
"The European Reformations",
"Meaning in History",
"The Prince",
"Pequeño Cerdo Capitalista: Inversiones para Hippies, Yuppies, y Bohemios",
"Doctor Faustus",
"The Road",
"Areopagitica, Of Education",
"Paradise Lost",
"Latin for the New Millenium",
"Stuff Matters",
"The Scopes Trial: A Brief History with Documents",
"Three Cups of Tea",
"Three Cups of Tea",
"The Trial of Tempel Anneke",
"The Boat Who Wouldn't Float",
"Colorless Tsukuru Tazaki and his Years of Pilgrimage",
"On the Genealogy of Morality",
"The Birth of Tragedy",
"Holy Bible, with the Apocrypha",
"2018 La Salida: Decadencia y renacimiento de Mexico",
"The Library Book",
"A Collection of Essays",
"Hermeneutics",
"The White Castle",
"The Christopher Parkening Guitar Method, Vol I",
"The Christopher Parkening Guitar Method, Vol II",
"In Light of India",
"An Intellectual History of Modern Europe",
"The Bell Jar",
"Phaedrus",
"The Republic",
"The Republic",
"The Logic of Scientific Discovery",
"The Ludwig Conspiracy",
"Medieval Women",
"Bhagavad Gita",
"The Nectar of Instruction",
"Renaissance Lives: Portraits of an Age",
"The Ancient and Medieval World",
"The Ancient and Medieval World",
"The Ancient and Medieval World",
"A Discourse on Inequality",
"Harry Potter and the Philosopher's Stone",
"The Ministry of Utmost Happiness",
"Celebrate Theory: Level 2",
"Fury",
"Joseph Anton: A Memoir",
"The Enchantress of Florence",
"The Ground Beneath Her Feet",
"The Moor's Last Sigh",
"An Outline of Philosophy",
"Power: The Role of Man's Will to Power in the World's Economic and Political Affairs",
"The Dragons of Eden",
"Confessions",
"The Gospel According to Jesus Christ",
"Dead Certainties",
"Me Talk Pretty One Day",
"The Bookseller of Kabul",
"The Idea of Justice",
"Letters from a Stoic",
"Two Faces of Oedipus",
"Two Faces of Oedipus",
"Flight Instructor Rating for Pilots",
"An Equal Music",
"The Golden Gate",
"A Midsummer Night's Dream",
"Anthony and Cleopatra",
"Hamlet",
"Henry V",
"Richard II",
"The Two Gentlemen of Verona",
"The Winter's Tale",
"Frankenstein",
"Essays and Aphorisms",
"The Cambridge Companion to Paradise Lost",
"Silman's Complete Endgame Course: From Beginner to Master",
"The Theory of Moral Sentiments",
"The Book of Mormon: Another Testament of Jesus Christ",
"Guitar Theory Workbook: An Easy Guide to the Basics of Music Theory",
"The New Cambridge History of India: Vijayangara",
"The Blue Light Project",
"Poems of Tennyson 1829 - 1868",
"TI-84/TI-84 Plus",
"Somanatha: The Many Voices of a History",
"The Past as Present: Forging Contemporary Identities Through History",
"Holy Bible",
"Collected Poems",
"The Inward Animal",
"A Confederacy of Dunces",
"The French Worker: Autobiographies from the Industrial Era",
"The Adventures of Huckleberry Finn",
"The Crusades: A Very Short Introduction",
"If You Write: A Book About Art, Independence, and Spirit",
"Vaideology: Basic Music Theory for Guitar Players",
"Classical Guitar Solos for All Occasions",
"Granta 138",
"The Financial Lives of the Poets",
"The Zero",
"The Island of Doctor Moreau",
"Leaves of Grass",
"Dungeon Master's Guide",
"Monster Manual",
"The Book Thief",
"Foundation",
"Prelude to Foundation",
"Forward The Foundation",
"Foundation and Empire",
"Second Foundation",
"Foundation's Edge",
"Foundation and Earth",
"The Best of H.P. Lovecraft",
"Born a Crime",
"Genghis Khan and the Making of the Modern World",
"Talking to Strangers",
"Mythos",
"Renaissance Lives",
"Oryx and Crake",
"Terminal World",
"Heroes",
"Starship Troopers",
"The Adventures of Sherlock Holmes",
"Station Eleven",
"Failure Is Not An Option",
"Dune",
"Ancillary Justice",
"The Complete Essays",
"Madness & Civilization",
"The Crusades Through Arab Eyes",
"The Art of the Infinite",
"The Universe in a Nutshell",
"How Everything Works",
"Children of Ruin",
"Children of Time",
"The Bomber Mafia",
"The Hitchhiker's Guide to the Galaxy",
"If Toy Tell",
"Thinking in Systems",
];